upgrade: increase coverage for upgrade.factory.js
crowbar/crowbar-ui pull request #101
Opened 2016-12-07 12:13 UTC by Itxaka

2016-12-08 11:31 UTC, santiph commented on assets/app/data/crowbar/services/upgrade.factory.spec.js
> +        mockedConnectDatabaseServerResponse = {
How is this different to `mockedNewDatabaseServerResponse` from line 12?

2016-12-08 11:42 UTC, Itxaka commented on assets/app/data/crowbar/services/upgrade.factory.spec.js
> +        mockedConnectDatabaseServerResponse = {
Its not, but for the cost of one var we can visually separate them in the tests for easier comprehension of what it refers to.

2016-12-08 12:22 UTC, skazi0 commented on assets/app/data/crowbar/services/upgrade.factory.spec.js
> +        mockedConnectDatabaseServerResponse = {
I would change it to `mockedConnectDatabaseServerResponse = mockedNewDatabaseServerResponse`. This gives us the effect of separation as you mentioned but also shows that at the moment the responses are identical.

2016-12-08 12:26 UTC, skazi0 requested changes
small nit as commented

2016-12-09 11:43 UTC, Itxaka commented on assets/app/data/crowbar/services/upgrade.factory.spec.js
> +        mockedConnectDatabaseServerResponse = {
done!

2016-12-09 12:46 UTC, Itxaka commented
Need rebase after https://github.com/crowbar/crowbar-ui/pull/104 is in

2016-12-12 10:47 UTC, skazi0 approved these changes

2016-12-13 10:09 UTC, santiph commented
No issues found, approved

2016-12-13 10:09 UTC, merged