[WIP] upgrade: error handling
crowbar/crowbar-ui pull request #107
Opened 2016-12-15 14:10 UTC by Itxaka

2016-12-16 10:38 UTC, Itxaka commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) UI: Generic error handling (landing page)](https://trello.com/c/oo5N6XNL/204-3-ui-generic-error-handling-landing-page)

2016-12-20 11:54 UTC, skazi0 requested changes

2016-12-20 11:54 UTC, skazi0 commented on assets/app/widgets/suse-modal/suse-modal.directive.js
> +                        $('#suseModal').modal('show');
Why not work on the `elem` object passed to the link function here?

2016-12-21 09:42 UTC, santiph requested changes

2016-12-21 09:42 UTC, santiph commented on assets/app/widgets/suse-modal/suse-modal.directive.js
> +    function suseModal($uibModal) {
`suseModal.$inject = ['$uibModal'];`

2016-12-21 09:42 UTC, santiph commented on assets/app/widgets/suse-modal/suse-modal.directive.js
> +                            controller: function($uibModalInstance, $scope){
I think `$inject` will also be needed for this controller when minified

2016-12-21 09:42 UTC, santiph commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        button.btn.btn-default(type='button', ng-click='dismiss()') Close
missing new line at the end of the file

2016-12-21 09:42 UTC, santiph commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        h4#suseModalLabel.modal-title {{ error.title }}
Please keep in mind that more than one suse-modal could be invoked in the same page. Is an Id going to be enough?
Also, one way data binding?

2016-12-21 09:42 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +suse-modal(error="upgradeLandingVm.error")
I think the controller should be the one creating/deleting modals as error appears.

2016-12-21 11:09 UTC, skazi0 commented on assets/app/features/upgrade/templates/landing-page.jade
> +suse-modal(error="upgradeLandingVm.error")
The idea is that the directive will encapsulate the modal. The controller will be just used to bind the directive with the error source. Controllers should not create/delete view elements.

2016-12-21 11:22 UTC, Itxaka commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        h4#suseModalLabel.modal-title {{ error.title }}
How is that gonna work? You can only show one modal per page (unless you want to show several at the same time, which is probably terrible UI/UX) and in every page that we have, we call something then continue or fail. Is in that fail when we show the modal with the appropiate error/errors aggregated. 


So basically check -> failure -> modal -> recheck and start again. 

I dont see where we could have more than one modal invoked. This way we reuse the same modal to push and show the error that we want to show.

2016-12-21 11:24 UTC, Itxaka commented on assets/app/widgets/suse-modal/suse-modal.directive.js
> +    function suseModal($uibModal) {
Good point!

2016-12-21 11:29 UTC, santiph commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        h4#suseModalLabel.modal-title {{ error.title }}
`suse-modal` sounds generic enough to be also used by a login form, not just errors.
As a suse directive, it should be generic enough to be reused in other pages/projects/contexts, and there is my concern

2016-12-21 11:36 UTC, Itxaka commented on assets/app/widgets/suse-modal/suse-modal.directive.js
> +                            controller: function($uibModalInstance, $scope){
also done!

2016-12-21 11:36 UTC, Itxaka commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        button.btn.btn-default(type='button', ng-click='dismiss()') Close
done

2016-12-21 11:43 UTC, Itxaka commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        h4#suseModalLabel.modal-title {{ error.title }}
Is that a real use case for this? Im pretty sure a login form will require much more code than what this is now. 

Lets think of the now instead of creating stuff to cover 99% of the use cases, because in the end those rarely happen. I can change the name to be upgradeModal if you want.

2016-12-22 08:43 UTC, skazi0 commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        h4#suseModalLabel.modal-title {{ error.title }}
I would rather call this something like `suse-error-modal` as this is the current use case.

2016-12-22 08:43 UTC, skazi0 approved these changes

2016-12-22 11:25 UTC, Itxaka commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        h4#suseModalLabel.modal-title {{ error.title }}
just removed it, it was not used for anything anyway

2016-12-22 11:28 UTC, santiph requested changes

2016-12-22 11:28 UTC, santiph commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        button.btn.btn-default(type='button', ng-click='dismiss()') Close
Missing translation

2016-12-22 11:29 UTC, santiph requested changes

2016-12-22 11:29 UTC, santiph commented on assets/app/widgets/suse-modal/suse-modal.directive.jade
> +        button.btn.btn-default(type='button', ng-click='dismiss()') Close
Missing translation

2016-12-22 11:49 UTC, santiph approved these changes

2016-12-23 11:25 UTC, merged