upgrade: Asynchronous StopServices
crowbar/crowbar-ui pull request #109
Opened 2016-12-20 11:15 UTC by skazi0

This is just a rough-cut update of the UI to enable testing of the async stopping of services.

2016-12-20 11:35 UTC, Itxaka commented on assets/app/features/upgrade/upgrade.constants.js
> +        .constant('SERVICES_TIMEOUT_INTERVAL', 1000)
Isnt one second a bit aggresive? On a slow server it might take more than one second just to get the http response from the api. Would this lead to a non-ending cascading of requests being fired?

2016-12-20 11:42 UTC, skazi0 commented on assets/app/features/upgrade/upgrade.constants.js
> +        .constant('SERVICES_TIMEOUT_INTERVAL', 1000)
I have no idea how much time stopping services take. Most of those constants are meant to be tuned before release. Note that this interval is end-to-start time so it doesn't cause cascading. New check is scheduled only after successful response from the previous one.

2016-12-20 14:52 UTC, santiph commented on assets/app/features/upgrade/upgrade.constants.js
> +        .constant('SERVICES_TIMEOUT_INTERVAL', 1000)
`services` is too wide and doesn't reference to OpenStack ONLY

2017-01-09 10:12 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) UI: Generic error handling (stop services)](https://trello.com/c/516g9bhP/220-3-ui-generic-error-handling-stop-services)

2017-01-11 11:09 UTC, skazi0 commented on assets/app/features/upgrade/upgrade.constants.js
> +        .constant('SERVICES_TIMEOUT_INTERVAL', 1000)
renamed

2017-01-12 10:51 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [UI: adapt the "services" step integration to use the asynchronous API](https://trello.com/c/4tuPNg3J/2131-ui-adapt-the-services-step-integration-to-use-the-asynchronous-api)

2017-02-01 13:05 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-openstack-services.controller.js
> +            vm.errors = errorResponse.data;
Arent we missing here the `UNEXPECTED_ERROR_DATA` stuff that we do in other places?

```
   if (angular.isDefined(errorResponse.data.errors)) {
                            vm.errors = errorResponse.data;
                        } else {
                            vm.errors = UNEXPECTED_ERROR_DATA;
                        }
```

2017-02-01 13:06 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-openstack-services.controller.js
> +            vm.errors = errorResponse.data;
Same as above

2017-02-01 13:06 UTC, Itxaka requested changes
Not usre if the unexpected_error_data handling is missing in purpouse?

2017-02-01 13:23 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [#UI: 11 Upgrade: Database Backup Service Integration](https://trello.com/c/POvmmtlF/2109-ui-11-upgrade-database-backup-service-integration)

2017-02-01 13:25 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-openstack-services.controller.js
> +            vm.errors = errorResponse.data;
error handling is a separate card

2017-02-01 13:44 UTC, skazi0 commented
Error handling is going to be implemented under another trello card.

2017-02-01 15:41 UTC, Itxaka approved these changes

2017-02-02 08:57 UTC, merged