Update node's static state machine
crowbar/crowbar-ui pull request #110
Opened 2016-12-20 17:48 UTC by santiph

Add session to static service in order to simulate each steps and status.
Missing: nodes_upgrade progress (`current_node`, `remaining_nodes` and `upgraded_nodes`)

2016-12-21 11:13 UTC, Itxaka commented
Its looking good to me. Unfortunately, does this means that we need to change all the tests? They are all failing :(

2016-12-21 11:19 UTC, skazi0 commented
Only one test is failing (travis coloring is misleading). This dummy backend is not used in the tests so I'm not sure what's going on there.

2016-12-23 12:20 UTC, santiph commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Implement Upgrade UI (part 4/4)](https://trello.com/c/SLPZwWRu/201-3-implement-upgrade-ui-part-4-4)

2016-12-23 12:45 UTC, Itxaka approved these changes
looks good to me

2017-01-04 10:13 UTC, skazi0 requested changes
Please add documentation on how to operate this state machine (e.g. reset the session).

2017-01-04 10:41 UTC, Itxaka requested changes
Please remove the console.log and the commented console.log

2017-01-04 10:41 UTC, Itxaka commented on helpers/upgradeSession.js
> +        //console.log('========== Restoring Upgrade Status object');
leftovers should be removed

2017-01-04 10:41 UTC, Itxaka commented on helpers/upgradeSession.js
> +        //console.log('++++++++++ New upgrade Status object created');
same

2017-01-04 10:41 UTC, Itxaka commented on helpers/upgradeStatus.model.js
> +    console.log('Complete current step: ' + currentStepName);
console.log should be removed

2017-01-04 10:41 UTC, Itxaka commented on helpers/upgradeStatus.model.js
> +        console.log('Setting as passed:' + upgradeSteps[i]);
same

2017-01-04 10:41 UTC, Itxaka commented on routes/api/upgrade.js
> +    console.log('---- Step: %s - Status: %s', upgradeModel.getCurrentStepName(), upgradeModel.getCurrentStep().status);
more console.log

2017-01-05 09:46 UTC, matelakat commented
There is a merge commit in the list of commits. The commit messages also do not explain the reason for the changes, please add sensible commit messages. -1 from me.

2017-01-05 09:46 UTC, matelakat requested changes
Please fix the commits, add sensible commit messages.

2017-02-16 19:22 UTC, jsuchome commented
@skazi0 is this still relevant?

2017-02-17 09:18 UTC, skazi0 commented
@jsuchome overall we will probably need something like this if we need to extend the development of this UI some time, but this PR seems to be incomplete and I don't need it as I can do the testing with a real cloud.

2017-04-06 12:01 UTC, jsuchome commented
@skazi0 so can we just close it or does it have value to keep it open?

2017-04-06 12:27 UTC, skazi0 commented
@jsuchome I think we can close it. It diverged too much from the rest.

2017-04-07 07:13 UTC, jsuchome commented
So closing

2017-04-07 07:13 UTC, closed without merging