upgrade: Add error handling to the admin repo check page
crowbar/crowbar-ui pull request #114
Opened 2017-01-04 10:26 UTC by Itxaka

2017-01-04 10:26 UTC, Itxaka commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) UI: Generic error handling (admin repo check)](https://trello.com/c/4eO0PsXW/206-3-ui-generic-error-handling-admin-repo-check)

2017-01-04 11:22 UTC, skazi0 requested changes

2017-01-04 11:22 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                            vm.error = { title: 'Some repositories are not ready', body: repoErrors.join(', ') };
please move those texts to translations file (e.g. like here: https://github.com/crowbar/crowbar-ui/pull/115)

2017-01-04 11:22 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                        vm.error = { title: 'Error while querying the API', body: errorRepoChecksResponse.data.errors }
ditto + we need to decide on the format of `body` (string or what?)

2017-01-04 12:01 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                            vm.error = { title: 'Some repositories are not ready', body: repoErrors.join(', ') };
Umm, I rather move them when we have the final text, that way we can have the TODO in there and its easily identifiable. We cannot set comments on the json file unfortunately, so Im worried that setting a temporal text in there may get missed. Thoughts?

2017-01-04 12:59 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                            vm.error = { title: 'Some repositories are not ready', body: repoErrors.join(', ') };
This or add the translations and create a followup card for updating the translations.

2017-01-05 10:02 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                            vm.error = { title: 'Some repositories are not ready', body: repoErrors.join(', ') };
There is already a not-translated string merged as part of a previous PR, so I rather create a card to track this and change them when there is consensus on the titles/body style and so on.

2017-01-05 10:50 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                            vm.error = { title: 'Some repositories are not ready', body: repoErrors.join(', ') };
ok

2017-01-05 10:50 UTC, skazi0 approved these changes

2017-01-05 10:57 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                            vm.error = { title: 'Some repositories are not ready', body: repoErrors.join(', ') };
https://trello.com/c/Mpu84gVE/246-ui-error-messages-definitions

2017-01-05 10:58 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                        vm.error = { title: 'Error while querying the API', body: errorRepoChecksResponse.data.errors }
same as above: https://trello.com/c/Mpu84gVE/246-ui-error-messages-definitions

2017-01-05 11:26 UTC, Itxaka commented
Need to update to be in sync with https://github.com/crowbar/crowbar-ui/pull/115

2017-01-05 11:34 UTC, Itxaka commented
@skazi0 updated to be in sync with your changes!

2017-01-18 08:45 UTC, skazi0 requested changes
some adjustment is still needed to match recent changes in common error handling

2017-01-18 08:45 UTC, skazi0 commented on assets/app/features/upgrade/templates/administration-repositories-checks-page.jade
> +suse-modal(error="upgradeAdminRepoChecksVm.error")
please add `translation-prefix="upgrade.errors"` for proper error code scoping

2017-01-18 08:45 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                            vm.error = { title: 'Some repositories are not ready', body: repoErrors.join(', ') };
After some discussion around the implementation of nodes repo checks, we decided that showing error popup for failed repos doesn't bring much benefit as the same information will be displayed in the main step page anyway (red marks).

2017-01-18 08:45 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                        vm.error = { title: 'Error while querying the API', body: errorRepoChecksResponse.data.errors }
After recent changes leading to unify error formats around the application, expected format for error modal input is the "common format" used in other places.
See: https://github.com/crowbar/crowbar-ui/pull/117 and https://github.com/crowbar/crowbar-ui/pull/119

2017-01-19 10:37 UTC, Itxaka commented
@skazi0 updated! Thanks for the feedback!

2017-01-19 13:37 UTC, skazi0 requested changes

2017-01-19 13:37 UTC, skazi0 commented on assets/app/features/upgrade/templates/administration-repositories-checks-page.jade
> +suse-modal(error="upgradeAdminRepoChecksVm.error", translation-prefix="upgrade.errors")
s/error/errors/

2017-01-20 09:31 UTC, Itxaka commented on assets/app/features/upgrade/templates/administration-repositories-checks-page.jade
> +suse-modal(error="upgradeAdminRepoChecksVm.error", translation-prefix="upgrade.errors")
wooops!

2017-01-20 10:15 UTC, skazi0 approved these changes

2017-01-20 10:16 UTC, merged