upgrade: internal steps were renamed to match crowbarctl subcommands
crowbar/crowbar-ui pull request #120
Opened 2017-01-12 12:44 UTC by MaximilianMeister

## depends on

https://github.com/crowbar/crowbar-core/pull/981

2017-01-12 12:44 UTC, MaximilianMeister commented
![](https://github.trello.services/images/mini-trello-icon.png) [rename crowbarctl upgrade command arguments to match the steps provided by the progress library](https://trello.com/c/g9Tk7kzj/257-rename-crowbarctl-upgrade-command-arguments-to-match-the-steps-provided-by-the-progress-library)

2017-01-16 08:26 UTC, jsuchome approved these changes

2017-01-17 09:09 UTC, skazi0 requested changes

2017-01-17 09:09 UTC, skazi0 commented on assets/app/data/crowbar/crowbar.constants.js
> -            admin_backup: 'admin_backup',
you need to also update the errors section in the language file (rebase if needed to get latest changes).

2017-01-17 09:39 UTC, skazi0 approved these changes

2017-01-17 10:27 UTC, merged