upgrade: Backend repo mapping for repochecks
crowbar/crowbar-ui pull request #124
Opened 2017-01-18 12:09 UTC by skazi0

Backend provides mapping product to repositories in the repochecks
responses. It can be used instead of the PRODUCTS_REPO_CHECKS_MAP
constant.

2017-01-18 12:09 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [crowbarctl should show nice names for missing repositories](https://trello.com/c/xr2UOZyN/261-crowbarctl-should-show-nice-names-for-missing-repositories)

2017-01-19 10:26 UTC, Itxaka approved these changes
Tested and works

2017-01-19 13:03 UTC, MaximilianMeister approved these changes
as far as I can judge

2017-01-20 14:12 UTC, MaximilianMeister requested changes
You need to remove the `Cloud` repo again, see https://github.com/crowbar/crowbar-core/pull/1006#issuecomment-274067570

2017-01-23 09:17 UTC, skazi0 commented
@MaximilianMeister `Cloud` repo removed

2017-01-23 09:54 UTC, MaximilianMeister approved these changes

2017-01-23 09:59 UTC, merged