upgrade: Show ha_configured precheck in UI
crowbar/crowbar-ui pull request #152
Opened 2017-03-01 13:16 UTC by skazi0

If HA is not configured, UI switched to "Normal" mode but didn't
explicitly say why. This info is returned in ha_configured precheck's
error data and is now displayed as other prechecks.

2017-03-01 13:16 UTC, skazi0 commented
@jsuchome please verify the texts

2017-03-01 13:17 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [crowbar-ui: show the output of ha_presence check](https://trello.com/c/8HJoxvvT/330-crowbar-ui-show-the-output-of-ha-presence-check)

2017-03-01 13:19 UTC, skazi0 commented
![zrzut ekranu z 2017-03-01 14-19-33](https://cloud.githubusercontent.com/assets/2458112/23461413/24b04038-fe8a-11e6-97f6-7db5206b7d8e.png)

2017-03-01 13:53 UTC, jsuchome commented on assets/app/features/upgrade/i18n/en.json
> +            "ha_configured": "Cloud is not Highly Available",
*Cloud configuration is not Highly Available*

2017-03-01 14:58 UTC, jsuchome commented on assets/app/features/upgrade/i18n/en.json
> +            "ha_configured": "Cloud is not Highly Available",
Please also add `"ha_not_installed": "High Available module is not present"`

2017-03-01 15:00 UTC, jsuchome requested changes
see comments

2017-03-01 15:34 UTC, Itxaka approved these changes
After the changes requested, good for me

2017-03-02 08:27 UTC, skazi0 commented on assets/app/features/upgrade/i18n/en.json
> +            "ha_configured": "Cloud is not Highly Available",
how about "High Availability module is not present" ?

2017-03-02 08:33 UTC, jsuchome commented on assets/app/features/upgrade/i18n/en.json
> +            "ha_configured": "Cloud is not Highly Available",
Right, that's better

2017-03-02 08:34 UTC, jsuchome commented on assets/app/features/upgrade/i18n/en.json
> +            "ha_configured": "Cloud is not Highly Available",
Or, maybe *Cloud is not  configured as Highly Available*

2017-03-02 08:43 UTC, skazi0 commented on assets/app/features/upgrade/i18n/en.json
> +            "ha_configured": "Cloud is not Highly Available",
OK, I also updated the text when "Normal" mode is chosen to the same wording.

2017-03-02 08:52 UTC, jsuchome approved these changes

2017-03-02 09:11 UTC, merged