upgrade: Label for non-KVM compute error
crowbar/crowbar-ui pull request #172
Opened 2017-03-28 13:34 UTC by jsuchome

Defined in https://github.com/crowbar/crowbar-core/pull/1189

2017-03-28 13:50 UTC, jsuchome commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) S58P4 bsc#1029847: Handle non-kvm compute nodes](https://trello.com/c/1Kb1AFzw/376-3-s58p4-bsc-1029847-handle-non-kvm-compute-nodes)

2017-03-29 07:21 UTC, skazi0 requested changes

2017-03-29 07:21 UTC, skazi0 commented on assets/app/features/upgrade/i18n/en.json
> +            "non_kvm_computes": "Non KVM compute nodes found",
AFAIK it should be "Non-KVM" not "Non KVM" (like in the commit/PR title)

2017-03-29 07:22 UTC, jsuchome commented on assets/app/features/upgrade/i18n/en.json
> +            "non_kvm_computes": "Non KVM compute nodes found",
I'll update it

2017-04-06 12:35 UTC, skazi0 approved these changes

2017-04-06 12:40 UTC, merged