Features/directives/checklist fix
crowbar/crowbar-ui pull request #28
Opened 2016-09-12 09:25 UTC by skazi0

2016-09-14 09:24 UTC, bisht-richa commented
Looks good.

2016-09-15 10:33 UTC, santiph commented on assets/app/widgets/crowbar-checklist/crowbar-checklist.directive.spec.js
> +            expect(angular.element(uls[0]).children().length).toEqual(_.size(scope.testChecks));
Shouldn't `_.size(scope.testChecks)` be `_.size(scope.testChecks.length)` instead?

2016-09-15 11:03 UTC, skazi0 commented on assets/app/widgets/crowbar-checklist/crowbar-checklist.directive.spec.js
> +            expect(angular.element(uls[0]).children().length).toEqual(_.size(scope.testChecks));
No. `scope.testChecks` is an object. If it was an array we would use `scope.testChecks.length` directly. To count properties of an object I chose `_.size(object)`.

2016-09-15 11:19 UTC, santiph commented on assets/app/widgets/crowbar-checklist/crowbar-checklist.directive.jade
> +        check-key='{{checkKey}}',
checkKey won't change here, please avoid two way data binding

2016-09-15 11:21 UTC, santiph commented on assets/app/widgets/crowbar-checklist/crowbar-checklist.directive.spec.js
> +                var itemElement = angular.element(li)
Missing semicolon.
Also, please use one `var` statement to declare multiple variables

2016-09-15 11:23 UTC, santiph requested changes
Please fix the var statement and consider this PR approved. Good job! 👍

2016-09-15 11:37 UTC, santiph commented
Approved

2016-09-15 11:37 UTC, santiph approved these changes

2016-09-15 11:37 UTC, merged