Added commom headers required by the API
crowbar/crowbar-ui pull request #50
Opened 2016-09-22 11:33 UTC by skazi0

2016-09-23 09:53 UTC, skazi0 commented
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lqn8yLQ0&#x2F;122-2-21-add-on-product-repo-checks-service-integration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (2) #21 Add-On Product Repo Checks: Service Integration</a>

2016-09-26 09:26 UTC, santiph commented on assets/app/data/services/upgrade/common-api.constants.js
> +        .constant('COMMON_API_HEADERS', {
Could you add the API version?
`COMMON_API2_HEADERS`

2016-09-26 09:27 UTC, santiph commented on assets/app/data/services/upgrade/common-api.constants.js
> +        .constant('COMMON_API_HEADERS', {
Also on the file name it'd be good to update it

2016-09-26 09:28 UTC, santiph requested changes
Good implementation, please address the name change before merging

2016-09-26 10:55 UTC, skazi0 commented on assets/app/data/services/upgrade/common-api.constants.js
> +        .constant('COMMON_API_HEADERS', {
done.

2016-09-26 11:56 UTC, merged