Added support for syncing UI with remote cloud.
crowbar/crowbar-ui pull request #51
Opened 2016-09-22 13:19 UTC by skazi0

For testing with real mkcloud setup running on a remote host.
Run: `gulp --synccloudhost=<fqdn.of.admin.node>`.

2016-09-23 09:51 UTC, skazi0 commented
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OTD4FMsJ&#x2F;127-3-update-crowbar-ui-development-environment"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (3) Update Crowbar-UI Development environment</a>

2016-09-23 09:55 UTC, santiph commented on cloud.conf.json.template
> +    "default": {
Please, lets use some reference to cloud 6, 7 and cloud 7 crowbar init.
Also, we need 3 different ports for the ssh connection on each machine

2016-09-23 09:57 UTC, santiph commented on gulp/rsync.js
> +    var cloudconfig = cloudconfigs[cloudid];
Please move `cloudid` and `cloudconfig` to line 7?
Also, camelcase

2016-09-23 09:57 UTC, santiph requested changes
Looks very good so far. I left a couple of comments to be addressed

2016-09-23 10:00 UTC, santiph commented on gulp/rsync.js
> +    var cloudid = gutil.env.synccloud || 'default';
Please, use dashes on `sync-cloud` to match gulp's parameters convention

2016-09-23 10:02 UTC, skazi0 commented on cloud.conf.json.template
> +    "default": {
You can name your clouds any way you like. For multiple ports just add multiple cloud entries with the same host but different ports.

2016-09-23 10:16 UTC, skazi0 commented on gulp/rsync.js
> +    var cloudconfig = cloudconfigs[cloudid];
done.

2016-09-23 10:16 UTC, skazi0 commented on gulp/rsync.js
> +    var cloudid = gutil.env.synccloud || 'default';
done.

2016-09-23 10:35 UTC, santiph approved these changes

2016-09-23 10:37 UTC, merged

2016-09-26 08:56 UTC, rsalevsky commented
Awesome that this got merged! I need to adapt the package in parallel to avoid conflicts.