Integrated Admin Server Backup page with backend.
crowbar/crowbar-ui pull request #54
Opened 2016-09-28 10:39 UTC by skazi0

Modified the logic to match the two-step backup creation and download implemented in the API.

The backup (and file) name required by the API is auto-generated in format: `upgrade-backup-yyyyMMddHHmmss.tar.gz`.

2016-09-28 10:40 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) #8 Backup Admin Server: Service Integration](https://trello.com/c/hw0n8t1G/129-1-8-backup-admin-server-service-integration)

2016-10-06 15:54 UTC, santiph requested changes
A couple of changes requested, please address them

2016-10-06 15:54 UTC, santiph commented on assets/app/data/services/upgrade/backup.factory.js
> +                url: '/api/crowbar/backups/' + id + '/download',
What about if Id is not provided?

2016-10-06 15:54 UTC, santiph commented on assets/app/data/services/upgrade/backup.factory.spec.js
> +            expect(upgradeBackupFactory.download).toEqual(jasmine.any(Function));
Please, separate this into its own `it()`

2016-10-06 15:54 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade7-backup.controller.js
> +            return value.replace(/"/g, '');
please, add comments to indicate what's being done and what's the intended result

2016-10-06 15:54 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade7-backup.controller.js
> +        function downloadBackup(backupInfo) {
Please, use backupId instead of backupInfo, there's no need to receive the full object

2016-10-06 15:54 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade7-backup.controller.spec.js
> +                });
Missing tests

2016-10-07 10:23 UTC, santiph commented on assets/app/data/services/upgrade/backup.factory.spec.js
> +            it('trows an exception', function () {
typo: "throws"

2016-10-07 10:24 UTC, santiph approved these changes
Looks good. Minor typo detected. Please fix it and consider this PR approved

2016-10-07 10:50 UTC, merged