Update rsync script and options
crowbar/crowbar-ui pull request #56
Opened 2016-10-04 15:32 UTC by santiph

New `--no-sync=true/false` option added to skip remote synchronisation completely.
Add new error handlers around the configuration file and its cloud options

2016-10-05 08:27 UTC, skazi0 requested changes
I'm not sure you need this much error handling in a script which is only a part of development environment and doesn't go into the product.
IMO, if there is a template for the config file, there's no need to check in the code if the actual config matches the template.

2016-10-05 08:27 UTC, skazi0 commented on gulp/rsync.js
> +    skypeRsync = 'Skypping rsync.';
Should be skip/Skipping.

2016-10-05 08:27 UTC, skazi0 commented on gulp/rsync.js
> +
Why was this blank line added?

2016-10-05 08:58 UTC, santiph commented on gulp/rsync.js
> +    skypeRsync = 'Skypping rsync.';
good catch

2016-10-05 08:58 UTC, santiph commented on gulp/rsync.js
> +
No need. I'll remove it

2016-10-05 09:00 UTC, santiph commented
@skazi0 I started adding an option to avoid rsync at all, and then continued handling other scenarios to help to eventually debug, just for fun
btw, I've updated the changes

2016-10-05 12:31 UTC, skazi0 commented on gulp/rsync.js
> +    skypeRsync = 'Skypping rsync.';
The typo is still there in the variable name.

2016-10-05 15:14 UTC, santiph commented on gulp/rsync.js
> +    skypeRsync = 'Skypping rsync.';
Should be updated now

2016-10-06 07:28 UTC, skazi0 commented on gulp/rsync.js
> +    skypeRsync = 'Skypping rsync.';
I'm not a native english speaker but I believe it should be `skipRsync` not `skipeRsync`.

2016-10-06 08:06 UTC, skazi0 approved these changes

2016-10-06 09:01 UTC, merged