Features/upgrade7/upgrade nodes/template
crowbar/crowbar-ui pull request #63
Opened 2016-10-13 10:58 UTC by bisht-richa

Created empty template for upgrade nodes page

2016-10-13 12:05 UTC, skazi0 approved these changes

2016-10-13 13:24 UTC, santiph requested changes
Minor change required on docblock... Please address it and consider this PR approved

2016-10-13 13:24 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-nodes.controller.js
> +    * This is the controller used on the Stop OpenStack Services page
This is the controller used on the Upgrade Nodes step, not Stop OpenStack Services

2016-10-17 12:19 UTC, santiph approved these changes

2016-10-17 13:47 UTC, rsalevsky requested changes
The commit message from the second commit is too long. Also it would be nice to make the first letter of the third commit message capital.

2016-10-18 08:25 UTC, merged