- Acomodate the code to the actual API response
crowbar/crowbar-ui pull request #66
Opened 2016-10-13 15:28 UTC by Itxaka

- Create a static fake api call to test the admin repocheck page
 - Acomodate the tests to the changes
 - Sync test data with API response
 - Change the repo keys to be in sync with how we use them on the node repo checks
 - Acomodate the controller to deal with the API returning a products view rather than a per-repo response.

2016-10-13 15:29 UTC, Itxaka commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) S49P19 #32 Admin Server Repo Checks: Service Integration](https://trello.com/c/oGniN5Lf/149-3-s49p19-32-admin-server-repo-checks-service-integration)

2016-10-14 09:44 UTC, santiph requested changes

2016-10-14 09:44 UTC, santiph commented on assets/app/features/upgrade/upgrade.constants.js
> +            'openstack': ['SLES-OpenStack-Cloud-7','SLES-OpenStack-Cloud-7-Updates']
Could NODES reuse the Admin definition somehow? I'd like to avoid code repetition.

2016-10-14 09:44 UTC, santiph commented on routes/api/crowbar/repocheck.js
> +var repo_correct = false;
Please declare new variables by reusing one single `var`

2016-10-14 09:44 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
>                      label: 'upgrade.steps.admin-repository-checks.repositories.codes.SLES_12_SP2'
Please, also update language keys to match the repo names

2016-10-14 09:46 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                                vm.repoChecks.checks[repo].status = repoChecksResponse.data[type]['available']
Is there any difference between `repoChecksResponse.data[type]['available']` and `repoChecksResponse.data[type].available`?

2016-10-14 09:48 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                                vm.repoChecks.checks[repo].status = repoChecksResponse.data[type]['available']
Nope, sorry, that is python style applied to javascript, I'll fix it to use `.available`

2016-10-14 09:48 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.spec.js
> +                /* eslint-disable no-undef */
Please add the constant to the globals in line 1 instead

2016-10-14 09:54 UTC, Itxaka commented on assets/app/features/upgrade/upgrade.constants.js
> +            'openstack': ['SLES-OpenStack-Cloud-7','SLES-OpenStack-Cloud-7-Updates']
Yup. Should consolidate both of them into just one constant. Incoming.

2016-10-14 10:26 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.spec.js
> +                /* eslint-disable no-undef */
done!

2016-10-14 10:26 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
> +                                vm.repoChecks.checks[repo].status = repoChecksResponse.data[type]['available']
done!

2016-10-14 10:26 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-administration-repositories-checks.controller.js
>                      label: 'upgrade.steps.admin-repository-checks.repositories.codes.SLES_12_SP2'
done!

2016-10-14 10:26 UTC, Itxaka commented on routes/api/crowbar/repocheck.js
> +var repo_correct = false;
done!

2016-10-14 10:26 UTC, Itxaka commented on assets/app/features/upgrade/upgrade.constants.js
> +            'openstack': ['SLES-OpenStack-Cloud-7','SLES-OpenStack-Cloud-7-Updates']
done!

2016-10-14 12:05 UTC, santiph requested changes

2016-10-14 12:05 UTC, santiph commented on routes/api/crowbar/repocheck.js
> +                        'SUSE OpenStack Cloud 7',
I think this should be updated to use same repository names listed in 
https://trello.com/c/oGniN5Lf/149-3-s49p19-32-admin-server-repo-checks-service-integration#comment-57f63b68212d25bfb1fd57af

2016-10-14 12:59 UTC, Itxaka commented on routes/api/crowbar/repocheck.js
> +                        'SUSE OpenStack Cloud 7',
Indeed, the api docs make this clear. I'll change it

2016-10-14 13:02 UTC, Itxaka commented on routes/api/crowbar/repocheck.js
> +                        'SUSE OpenStack Cloud 7',
Uh, actually the /api/crowbar/repocheck  docs indicate that this is correct this way:

```
{
  "os": {
    "available": true,
    "repos": {}
  },
  "cloud": {
    "available": false,
    "repos": {
      "x86_64": {
        "missing": [
          "SUSE OpenStack Cloud 7"
        ]
      }
    }
  }
}
```

2016-10-14 13:23 UTC, santiph commented on routes/api/crowbar/repocheck.js
> +                        'SUSE OpenStack Cloud 7',
That's what you should've changed as part of https://trello.com/c/sl8vHEaY/146-3-s49p14-bsc-999946-upgrade-check-for-repositories-on-admin-server-only-checks-for-product

2016-10-14 14:07 UTC, santiph approved these changes

2016-10-14 14:08 UTC, santiph commented
Approved

2016-10-14 14:08 UTC, merged