Features/upgrade7/steps sidebar
crowbar/crowbar-ui pull request #71
Opened 2016-10-18 09:01 UTC by bisht-richa

2016-10-18 12:06 UTC, santiph commented on assets/app/data/crowbar/steps.factory.js
> +                */
```
                /** 
                 * Update factory steps.active and steps.enabled to ture, 
                 * if the steps.state is equal to the current state 
                 */
```

2016-10-18 12:09 UTC, santiph commented on assets/app/data/crowbar/steps.factory.js
> +                } else {
The rest of the steps should not be active

2016-10-18 14:44 UTC, Itxaka commented
LGTM +1

2016-10-19 15:29 UTC, santiph commented
Looks good to me. Please @Itxaka @skazi0 could you review my commit for the directive's unit tests?
https://github.com/crowbar/crowbar-ui/pull/71/commits/3dc615c6b8867b33a697f3f4a2b813a3193e0e40

We're still missing unit test for the steps factory.

2016-10-19 15:44 UTC, Itxaka commented
Some of the commits have no info about whats in the commit:

```Merge branch 'features/upgrade7/steps-sidebar' of https://github.com/crowbar/crowbar-ui into features/upgrade7/steps-sidebar```

Can they be fixed to actually say what was changed/added/removed please?

Would also be good to merge https://github.com/crowbar/crowbar-ui/pull/74 with this so we can get full testing of the upgrade.controller.js

2016-10-19 17:22 UTC, skazi0 requested changes
nitpicks

2016-10-19 17:22 UTC, skazi0 commented on assets/app/widgets/crowbar-upgrade-steps/crowbar-upgrade-steps.directive.spec.js
> +    var directiveElement = 123,
why initialize this variable?

2016-10-19 17:22 UTC, skazi0 commented on assets/app/widgets/crowbar-upgrade-steps/crowbar-upgrade-steps.directive.spec.js
> +            expect(listItems.length).toEqual(2);
maybe compare to size of steps list in scope?

2016-10-20 13:40 UTC, santiph commented on assets/app/widgets/crowbar-upgrade-steps/crowbar-upgrade-steps.directive.spec.js
> +    var directiveElement = 123,
Oops. Needs to be removed.

2016-10-20 13:40 UTC, santiph commented on assets/app/widgets/crowbar-upgrade-steps/crowbar-upgrade-steps.directive.spec.js
> +            expect(listItems.length).toEqual(2);
Good catch. will update

2016-10-20 16:17 UTC, skazi0 approved these changes

2016-10-21 09:00 UTC, Itxaka approved these changes

2016-10-25 08:24 UTC, Itxaka commented on assets/app/features/upgrade/upgrade.module.js
> +        .module('crowbarApp.upgrade', ['ui.router', 'pascalprecht.translate', 'suseData']);
Question: where is `pascalprecht.translate` coming from and being used for? Is this different than `$translate`?

2016-10-25 08:27 UTC, Itxaka approved these changes
Still looking good to me!

2016-10-25 13:27 UTC, bisht-richa commented
Looks good 👍

2016-10-26 10:42 UTC, santiph commented on assets/app/features/upgrade/upgrade.module.js
> +        .module('crowbarApp.upgrade', ['ui.router', 'pascalprecht.translate', 'suseData']);
`pascalprecht.translate` is the module where the `$translate` resource is contained.
You can check https://angular-translate.github.io/ or https://angular-translate.github.io/docs/#/guide for more details, or ask me if you have more questions. :)

2016-10-26 10:43 UTC, merged

2016-10-26 10:54 UTC, santiph commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) S49P21 #5 Layout - Steps Sidebar](https://trello.com/c/HHfMzKPR/103-2-s49p21-5-layout-steps-sidebar)