Change the API route for admin repocheck
crowbar/crowbar-ui pull request #76
Opened 2016-10-19 14:57 UTC by Itxaka

Due to the movement of the admin repocheck to the upgrade namespace,
we need to change the route we use to call the api

Depends on https://github.com/crowbar/crowbar-core/pull/739

 - Move the call to the admin repo check to the proper namespace
 - Move the fake API route to the proper namespace

2016-10-19 14:58 UTC, Itxaka commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) S49P19 #32 Admin Server Repo Checks: Service Integration](https://trello.com/c/oGniN5Lf/149-3-s49p19-32-admin-server-repo-checks-service-integration)

2016-10-19 15:39 UTC, santiph requested changes
Crowbar Factory method and its test needs to be moved to the Upgrade Factory.

2016-10-19 15:39 UTC, santiph commented on assets/app/data/crowbar/services/crowbar.factory.js
(for some reason I cannot add this comment on line 12)
This method (`getRepositoriesChecks `) needs to be moved from crowbar factory to upgrade factory, as they're intended to be a reflection of the API entities.

2016-10-21 13:33 UTC, Itxaka commented on assets/app/data/crowbar/services/crowbar.factory.js
out of scope for this patch or wrong PR?

2016-10-21 13:42 UTC, Itxaka commented
Ready to review as dependant patch has been merged!

2016-10-21 14:20 UTC, santiph commented on assets/app/data/crowbar/services/crowbar.factory.js
I don't think so.
Repository checks for the admin server now is part of the upgrade API entity, not crowbar.
Therefore, in order to keep consistency, I think we should reflect that by moving the `getRepositoriesChecks` method from crowbar.factory.js into upgrade.factory.js

2016-10-24 08:39 UTC, Itxaka commented on assets/app/data/crowbar/services/crowbar.factory.js
Ahhh I see now! Indeed you are rigth, this should be moved into the appropiate place now that has changed places in the API

2016-10-24 09:45 UTC, santiph approved these changes

2016-10-24 09:45 UTC, santiph commented
Looks good to me now. :) Thanks!

2016-10-24 09:45 UTC, merged