Navigation: Next button behaviour
crowbar/crowbar-ui pull request #77
Opened 2016-10-20 12:58 UTC by Itxaka

Uses the steps factory to track and set the current step finished to track if a step is finished or not and allow the next button to be enabled or disabled.

This is based on PR https://github.com/crowbar/crowbar-ui/pull/71 so it depends on that one to get merged.

2016-10-20 13:01 UTC, Itxaka commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) S49P20 #6 Layout - Navigation bar](https://trello.com/c/LNr710jO/104-3-s49p20-6-layout-navigation-bar)

2016-10-20 18:05 UTC, skazi0 requested changes

2016-10-20 18:05 UTC, skazi0 commented on assets/app/features/upgrade/upgrade.controller.js
> +        vm.steps.list = upgradeStepsFactory.steps;
move it above to `vm.steps` initialization just like `stepFinished`.

2016-10-20 18:05 UTC, skazi0 commented on assets/app/data/crowbar/steps.factory.js
> +                isCompletedStep = true;
It took me some time to understand the logic of `isCompletedStep`. Not sure if there's a better name for this but maybe it should at least be described in a comment that this flag indicates that given step was already completed which will be reflected in the UI.
This is especially confusing and a bit redundant when connected with `setCurrentStepCompleted()` above.

2016-10-20 18:05 UTC, skazi0 commented on assets/app/features/upgrade/upgrade.controller.js
> +            $state.go(vm.steps.list[upgradeStepsFactory.activeStep.id + 1].state);
The whole `nextStep()` and `isLastStep()` belong in `upgradeStepsFactory`. The factory already uses `$state` and owns the steps list. They can be linked here just like the rest of `vm.steps`.

2016-10-20 18:05 UTC, skazi0 commented on assets/app/features/upgrade/upgrade.controller.js
> +            stepFinished: upgradeStepsFactory.stepFinished
Not sure what our convention is but we should try to keep the functions returning booleans named consistently. Here we have `isLastStep()` and `stepFinished()`.

2016-10-21 08:00 UTC, Itxaka commented on assets/app/features/upgrade/upgrade.controller.js
> +            $state.go(vm.steps.list[upgradeStepsFactory.activeStep.id + 1].state);
This actually comes from richa's PR, not this one. Stupid gituhb doent allow linked patches properly :/

2016-10-21 08:01 UTC, Itxaka commented on assets/app/data/crowbar/steps.factory.js
> +                isCompletedStep = true;
This actually comes from richa's PR, not this one. Stupid gituhb doent allow linked patches properly :/

Also I think that var is not used anywhere for anything at all and was already in the code, I guess for preparation for tracking the step completition, but Im not sure I understand the reasoning of it at all. Should be removed in future patches as I dont think is useful.

2016-10-21 08:01 UTC, Itxaka commented on assets/app/features/upgrade/upgrade.controller.js
> +        vm.steps.list = upgradeStepsFactory.steps;
This actually comes from richa's PR, not this one. Stupid gituhb doent allow linked patches properly :/

2016-10-21 09:18 UTC, santiph commented on assets/app/data/crowbar/steps.factory.js
> +                isCompletedStep = true;
This var was used in the prototype to mark the completed steps in green. See https://github.com/crowbar/crowbar-ui/blob/master/assets/app/widgets/crowbar-upgrade-steps/crowbar-upgrade-steps.directive.jade#L2

It's a miss from the cleanup card and will be removed on Richa's changes

2016-10-27 11:39 UTC, Itxaka commented
I kept breaking my git history while trying to rebase this properly, so I just extracted the commit, updated it and pushed a new PR: https://github.com/crowbar/crowbar-ui/pull/81

2016-10-27 11:39 UTC, closed without merging