Added basic integration for the cancel feature.
crowbar/crowbar-ui pull request #78
Opened 2016-10-20 15:57 UTC by skazi0

This is useful for testing the begin upgrade without a need for restoring previous cloud state.

2016-10-21 13:31 UTC, Itxaka approved these changes
Looking good!

2016-10-24 15:27 UTC, santiph requested changes

2016-10-24 15:27 UTC, santiph commented on assets/app/widgets/crowbar-upgrade-nav/crowbar-upgrade-nav.directive.js
> +    function CrowbarUpgradeNavController($state, upgradeFactory) {
Widgets, as they've been conceived, are meant to be reusable components across different projects in the future simply by adding the module as a dependency. Therefore, they should not depend on other modules, like `suseData` nor on the features modules to determine the states and consume the API.

Please, provide those attributes through the controller and their scopes.

2016-10-25 09:37 UTC, Itxaka approved these changes
Still looking good to me

2016-10-28 10:03 UTC, skazi0 commented
rebased

2016-11-14 16:31 UTC, santiph requested changes
Good implementation!
Please address the minor request so we don't lose track of them and consider this approved.

2016-11-14 16:31 UTC, santiph commented on assets/app/widgets/crowbar-upgrade-nav/crowbar-upgrade-nav.directive.jade
>    | Cancel Upgrade
translation needed

2016-11-14 16:31 UTC, santiph commented on assets/app/features/upgrade/upgrade.controller.js
> +                $state.go('upgrade-landing');
After cancelation, user needs to be redirected to crowbar dashboard.
Completely out of the scope of this PR, but I'd like to ask you to add a comment in the code and https://trello.com/c/aP3CKeqb/28-2-17-cancellation-routine-page-creation to not lose track of it

2016-11-14 16:31 UTC, santiph commented on assets/app/data/crowbar/services/upgrade.factory.spec.js
> +        });
When executed, it's supposed to also redirect the user to crowbar dashboard... Again, out of the scope, but I'd appreciate a comment in the code and the trelo card: https://trello.com/c/aP3CKeqb/28-2-17-cancellation-routine-page-creation

2016-11-15 09:47 UTC, skazi0 commented on assets/app/data/crowbar/services/upgrade.factory.spec.js
> +        });
The redirect should be done in the controller so the service doesn't need any changes.

2016-11-15 09:47 UTC, skazi0 commented on assets/app/features/upgrade/upgrade.controller.js
> +                $state.go('upgrade-landing');
Comment added in code. I don't have write access to this trello so can't do anything there.

2016-11-25 12:08 UTC, Itxaka commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) S51P10 (S50P9 S49P20) #6 Layout - Navigation bar](https://trello.com/c/LNr710jO/104-3-s51p10-s50p9-s49p20-6-layout-navigation-bar)

2016-11-25 13:18 UTC, santiph approved these changes

2016-11-25 13:19 UTC, santiph commented
Approved as a temporary solution to be properly implemented (or completely removed, depending on the PO decision) in a future sprint

2016-11-25 13:19 UTC, merged