Navigation: next button behaviour
crowbar/crowbar-ui pull request #81
Opened 2016-10-27 11:39 UTC by Itxaka

- Use the step factory to track and set the step status to finished
 - Link the steps directive to enable/disable the next button based on the step status
 - Set stepCompleted in all the individual steps on completition

2016-10-27 11:40 UTC, Itxaka commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) S49P20 #6 Layout - Navigation bar](https://trello.com/c/LNr710jO/104-3-s49p20-6-layout-navigation-bar)

2016-10-27 11:54 UTC, skazi0 requested changes

2016-10-27 11:54 UTC, skazi0 commented on assets/app/features/upgrade/upgrade.controller.js
> +            stepFinished: upgradeStepsFactory.stepFinished
shouldn't it be `isStepFinished()`? (or whatever comes out of previous comment)

2016-10-27 11:54 UTC, skazi0 commented on assets/app/features/upgrade/steps.factory.js
> +            isStepFinished: isStepFinished
Maybe change this to `isCurrentStepCompleted` for consistency with `setCurrentStepCompleted`?

2016-10-27 12:10 UTC, Itxaka commented on assets/app/features/upgrade/upgrade.controller.js
> +            stepFinished: upgradeStepsFactory.stepFinished
THANK YOU!

I knew it was missing somewhere and could not find it for the life of me.

2016-10-27 12:10 UTC, Itxaka commented on assets/app/features/upgrade/steps.factory.js
> +            isStepFinished: isStepFinished
Good point, will change it!

2016-11-08 09:21 UTC, skazi0 approved these changes

2016-11-08 09:41 UTC, merged