WIP: Test angular-file-saver for the download files
crowbar/crowbar-ui pull request #82
Opened 2016-10-27 12:57 UTC by Itxaka

As pointed by @skazi0 angular-file-saver makes the downloading stuff pretty easy and it works cross-browser, fixing https://github.com/crowbar/crowbar-ui/issues/32 and probably any other issue with IE browsers.

This is only a run test, tests doesn't pass and there is no new tests done for the different functionality but its so @santiph can weight on what he thinks about this and if we should go forward with this or not.

2016-10-28 09:33 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.js
> +                            backupBlob = new Blob([response.data], {type: contentType});
Depending on the portability requirements (i.e. how old browsers need to be supported), we can make it even simpler: if you set `responseType: 'blob'` in `crowbar-backup.factory.js` you will get `response.data` already in blob format and you can drop the whole manual `Blob` object creation.

`Blob` has pretty decent support in modern desktop browsers: https://developer.mozilla.org/en-US/docs/Web/API/Blob#Browser_compatibility

2016-10-28 09:48 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.js
> +                            backupBlob = new Blob([response.data], {type: contentType});
I thougth that to trigger the download of zip files and binary files in general you were forced to set the `arraybuffer` responseType?

2016-10-28 09:51 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.js
> +                            backupBlob = new Blob([response.data], {type: contentType});
Hmmm... haven't heard about such requirement. I tested `responseType: blob` in current FF and Chrome and it works correctly.

2016-11-03 17:13 UTC, Itxaka commented
@skazi0 ready for a second round of checks, made the tests work with the new fileSaver, used blob as you suggested and removed non used code.

2016-11-04 10:01 UTC, skazi0 reviewed
small nits in the tests. besides that, looks good.

2016-11-04 10:01 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.js
> +        'Blob'
is this still needed?

2016-11-04 10:01 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.spec.js
> +                          mockedDownloadResponse.data, 'crowbarBackup'
Since this test is about the filename, I'd put jasmine.anything() as the first argument. The data can be a separate test.

2016-11-04 10:01 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.spec.js
> +                          mockedDownloadResponse.data, 'crowbarBackup'
You can use this place to do some basic blackbox testing of `extractFilename()`, i.e. expect the actual filename from headers here.

2016-11-07 11:55 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) S50P12 (S49P13) #8 Backup Admin Server: Service Integration](https://trello.com/c/hw0n8t1G/129-1-s50p12-s49p13-8-backup-admin-server-service-integration)

2016-11-07 13:02 UTC, skazi0 approved these changes

2016-11-07 13:12 UTC, matelakat approved these changes

2016-11-08 11:04 UTC, skazi0 commented
@rsalevsky this adds an npm dependency: https://github.com/crowbar/crowbar-ui/pull/82/files#diff-0a08a7565aba4405282251491979bb6bR27 please confirm it's ok from the packaging point of view

2016-11-14 16:21 UTC, santiph requested changes
Please, also include this dependency in the core module, so it can be reused on future projects
`assets/app/core/crowbar-core.module.js`

2016-11-14 16:21 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.spec.js
> +                          jasmine.anything(), 'crowbarBackup'
4 spaces please. Hasn't this been caught by travis?

2016-11-14 16:21 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.spec.js
> -                    it('click() method should have been triggered to download the backup', function () {
Why removed?

2016-11-14 16:21 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.spec.js
> +                          mockedDownloadResponse.data, jasmine.anything()
could this `anything()` be more specific?

2016-11-14 16:21 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.spec.js
> +                          jasmine.anything(), 'crowbarBackup'
Also, could `anything()` be more specific?

2016-11-14 16:29 UTC, rsalevsky commented
I have to update the package after merging this. So I would suggest once @santiph approved I will merge it and update the package.

2016-11-15 09:03 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.spec.js
> -                    it('click() method should have been triggered to download the backup', function () {
This is the whole beauty of using library instead of self-crafted direct solution: you don't need to test the internals of the library, just make sure that library functions are called (`expect(FileSaver.saveAs).toHaveBeenCalledWith(...)`)

2016-11-22 07:29 UTC, Itxaka commented
Thank you @skazi0 for updating the PR! :+1: 

@santiph can we merge this?

2016-11-23 09:41 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-backup.controller.spec.js
> -                    it('click() method should have been triggered to download the backup', function () {
You're right. I see it now

2016-11-23 09:41 UTC, santiph commented
Looks good so far. Please rebase it and I'll do a final review.

2016-11-23 10:09 UTC, Itxaka commented
rebased!

2016-11-23 10:39 UTC, Itxaka commented
Fixes issues that came from rebasing. Tested on both firefox+chrome. Looking good!

2016-11-23 10:56 UTC, santiph approved these changes

2016-11-23 10:56 UTC, merged