Switch from /api/crowbar/upgrade to /api/upgrade.
crowbar/crowbar-ui pull request #83
Opened 2016-11-09 12:43 UTC by skazi0

The overall upgrade status API at /api/upgrade gives more details about
the situation in the backend and is implemented also in crowbar-init.
This is important during admin server upgrade as crowbar is shut down
during the upgrade and can't provide status information.

This change switches from /api/crowbar/upgrade to /api/upgrade in the
context of admin server upgrade. The old service for accessing crowbar
upgrade status is not removed.

2016-11-14 13:28 UTC, santiph requested changes

2016-11-14 13:28 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-upgrade-administration-server.controller.js
> +                        vm.adminUpgrade.completed = response.data.steps.admin_upgrade.status == 'passed';
Could `passed` and `running` be stored as constants?

2016-11-14 13:28 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-upgrade-administration-server.controller.spec.js
> +                    status: 'pending',
Shouldn't `upgrade_prechecks`, `admin_backup` and `admin_repo_checks` be `passed` instead??

2016-11-14 13:28 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-upgrade-administration-server.controller.spec.js
> +                    status: 'pending',
Shouldn't `upgrade_prechecks`, `admin_backup` and `admin_repo_checks` be `passed` instead??

2016-11-14 13:28 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-upgrade-administration-server.controller.spec.js
> +                    status: 'pending',
Shouldn't `upgrade_prechecks`, `admin_backup` and `admin_repo_checks` be `passed` instead??
or current_step be set to upgrade_prechecks?

2016-11-14 13:48 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-upgrade-administration-server.controller.spec.js
> +                    status: 'pending',
can be.

2016-11-14 13:49 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-upgrade-administration-server.controller.js
> +                        vm.adminUpgrade.completed = response.data.steps.admin_upgrade.status == 'passed';
they are used only once so I don't think it's needed.

2016-11-18 10:51 UTC, santiph approved these changes

2016-11-18 10:51 UTC, merged