Async prepare
crowbar/crowbar-ui pull request #85
Opened 2016-11-15 13:29 UTC by skazi0

temporarily based on top of https://github.com/crowbar/crowbar-ui/pull/83

2016-11-15 13:29 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) S50P1 (S49P11) perform the prepare in the background (bsc#997293)](https://trello.com/c/YFa8WWef/144-5-s50p1-s49p11-perform-the-prepare-in-the-background-bsc-997293)

2016-11-17 09:39 UTC, skazi0 commented
Note that it's still based on https://github.com/crowbar/crowbar-ui/pull/83 so rebase will be needed before merging.

2016-11-18 08:37 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) S50P10 (S49P15) #11 Upgrade Admin Server: UI Story 2 - Service Integration](https://trello.com/c/PAkqYMEe/147-3-s50p10-s49p15-11-upgrade-admin-server-ui-story-2-service-integration)

2016-11-18 17:27 UTC, santiph requested changes
Partially reviewed. I'm still missing some files

2016-11-18 17:27 UTC, santiph commented on assets/app/data/crowbar/services/upgrade-status.factory.js
> +         *
missing docblock

2016-11-18 17:27 UTC, santiph commented on assets/app/data/crowbar/services/upgrade-status.factory.js
> +                url: '/api/upgrade',
this is part of the upgrade factory. Please move it there

2016-11-18 17:27 UTC, santiph commented on assets/app/data/crowbar/services/upgrade-status.factory.spec.js
> +                expect(upgradeStatusFactory.waitForStepToEnd).toEqual(jasmine.any(Function));
Same as line 176

2016-11-18 17:27 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +                        'upgrade_prepare',
We should have a centralised map to store the steps values and reuse them anywhere in the flow

2016-11-21 09:18 UTC, skazi0 commented on assets/app/data/crowbar/services/upgrade-status.factory.spec.js
> +                expect(upgradeStatusFactory.waitForStepToEnd).toEqual(jasmine.any(Function));
removed the other one.

2016-11-21 11:23 UTC, Itxaka commented on assets/app/data/crowbar/services/upgrade-status.factory.js
> +                        if (response.data.steps[step].status == 'passed') {
cant we use `STEP_STATES.passed` in the comparision?

2016-11-21 11:24 UTC, Itxaka commented
Wow! looking pretty good to me, only a small question but looking great!

2016-11-21 12:45 UTC, skazi0 commented on assets/app/data/crowbar/services/upgrade-status.factory.js
> +                        if (response.data.steps[step].status == 'passed') {
This is a bit tricky, `STEP_STATES` are defined in `upgrade.constants.js` which is loaded after the data services. I didn't find any better place to put these constants which would make them accessible to the `upgradeStatusFactory`. Any idea for this?

2016-11-21 13:00 UTC, Itxaka approved these changes

2016-11-21 13:00 UTC, Itxaka commented on assets/app/data/crowbar/services/upgrade-status.factory.js
> +                        if (response.data.steps[step].status == 'passed') {
Mmmh, I dont think that we should change it then. Doing acrobatics with the code just to use the constant in one place seems too much.

2016-11-23 09:39 UTC, santiph requested changes
minor clarifications requested

2016-11-23 09:39 UTC, santiph commented on assets/app/data/crowbar/services/upgrade-status.factory.js
> +         * Polling is done at given `pollingInterval` interval.
Great job explaining parameters!
Please, use the following to write docblocks: https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation
something like:
```
@param {type} step description
@param {type} onSuccess callback to be executed with last response from status API when waiting time finishes successfully.
@param {type} onError description
@param {number} pollingInterval Interval used to poll the upgrade status
@param {type} allowedDowntimeLeft description
```

2016-11-23 09:39 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-upgrade-administration-server.controller.js
> +                function (/*response*/) {
Could you add a comment clarifying this will be passed as success handler to the last promise?

2016-11-23 09:39 UTC, santiph commented on assets/app/features/upgrade/upgrade.constants.js
> +        .constant('ADMIN_UPGRADE_ALLOWED_DOWNTIME', 5 * 60 * 1000)
Where did you get this number from?

2016-11-23 10:52 UTC, skazi0 commented on assets/app/features/upgrade/upgrade.constants.js
> +        .constant('ADMIN_UPGRADE_ALLOWED_DOWNTIME', 5 * 60 * 1000)
5 minutes is just a blind guess for the time needed to reboot the admin server. This needs to be adjusted during testing.

2016-11-23 10:52 UTC, skazi0 commented
rebased.

2016-11-23 10:54 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-upgrade-administration-server.controller.js
> +                function (/*response*/) {
Do you write a comment for each callback you pass to standard `when()`? Client code should not explain how library works. The library's docs are for that.

2016-11-23 18:07 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-upgrade-administration-server.controller.js
> +                function (/*response*/) {
Actually, I do because I think it helps new angular developers to understand and read the code more clearly. On my experience, understanding Promises is one of the most frequent challenges people get...

But I see your point. It was definitely not a blocker, but a suggestion.

2016-11-23 18:07 UTC, santiph commented
I've sent an email requesting clarification on the timeout requirements.
Once confirmed, consider this approved.
Thanks for the hard work!

2016-11-23 18:08 UTC, santiph approved these changes

2016-11-24 09:14 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) S51P9 #Crowbar-ui: re-integrate landing page with latest API changes](https://trello.com/c/syDbFm5C/186-2-s51p9-crowbar-ui-re-integrate-landing-page-with-latest-api-changes)

2016-11-24 12:08 UTC, skazi0 commented on assets/app/features/upgrade/upgrade.constants.js
> +        .constant('ADMIN_UPGRADE_ALLOWED_DOWNTIME', 5 * 60 * 1000)
@vuntz suggested to change these to poll every 5-10sec and tolerate 20-30min downtime. PR updated.

2016-11-24 14:18 UTC, merged