New design > Layout
crowbar/crowbar-ui pull request #87
Opened 2016-11-24 15:15 UTC by santiph

Implement the new design proposed by ken to the Layout in the upgrade flow

2016-11-28 10:28 UTC, Itxaka commented
On the landing page, `SUSE OpenStack Cloud - provided by SUSE` its really close to the `Begin Upgrade` button. Seems like a bit of padding could help there.

Tested the rest, seems good to me, could not find any css issues.

2016-11-28 11:37 UTC, skazi0 requested changes

2016-11-28 11:37 UTC, skazi0 commented on assets/app/widgets/suse-footer/suse-footer.less
> +    color: #5F5F5F;
lesslint warning: "hexNotation: #5F5F5F should be written in lowercase."

2016-11-28 15:26 UTC, santiph commented on assets/app/widgets/suse-footer/suse-footer.less
> +    color: #5F5F5F;
Good catch! Thanks

2016-11-28 15:47 UTC, santiph commented
@Itxaka for the landing page adjustments we have https://trello.com/c/7aSYKiH4/189-3-s51p16-34-landing-page-new-design-frontend-service-integration ;)

2016-11-28 15:50 UTC, Itxaka approved these changes
Great stuff!

2016-11-29 08:30 UTC, skazi0 approved these changes

2016-11-29 09:24 UTC, merged

2016-12-15 11:29 UTC, santiph commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) S51P15 #35 Layout - New Design](https://trello.com/c/e15Q4gsi/188-2-s51p15-35-layout-new-design)

2016-12-20 11:04 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(?) Update UI Steps - move to New Design](https://trello.com/c/ZBzjl4Ay/218-update-ui-steps-move-to-new-design)