upgrade: New design for the landing page
crowbar/crowbar-ui pull request #96
Opened 2016-11-30 13:06 UTC by Itxaka

2016-11-30 14:32 UTC, santiph requested changes

2016-11-30 14:32 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.less
> +        float: left;
please use Bootstrap's helper classes for this
http://getbootstrap.com/css/#helper-classes-floats

2016-11-30 14:32 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                ng-disabled="!upgradeLandingVm.prechecks.completed || !upgradeLandingVm.prechecks.valid || upgradeLandingVm.prepare.running",
indentation

2016-12-01 09:21 UTC, Itxaka commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) S51P16 #34 Landing Page - New Design: Frontend & Service Integration](https://trello.com/c/7aSYKiH4/189-3-s51p16-34-landing-page-new-design-frontend-service-integration)

2016-12-01 12:08 UTC, Itxaka commented
Looks like this now:
![test](https://cloud.githubusercontent.com/assets/1447686/20793370/fe57de96-b7c6-11e6-8099-cbfaef615a8f.png)


Cant:
 - Get the big blue buttons to align with the text. Something to do with the h2 probably
 - Remove the decorations from the big blue buttons. Tried to override hover to not avail.

2016-12-02 12:37 UTC, Itxaka commented
Preview ![test2](https://cloud.githubusercontent.com/assets/1447686/20834224/73bb0ae6-b894-11e6-933f-68a0e66f87c8.png)

2016-12-05 11:09 UTC, santiph requested changes

2016-12-05 11:09 UTC, santiph commented on assets/app/widgets/crowbar-circle/crowbar-circle.less
> +  background-color: #00b2e2;
4 spaces indentation please

2016-12-05 11:09 UTC, santiph commented on assets/app/widgets/crowbar-circle/crowbar-circle.directive.js
> +        };
Missing `templateUrl` attribute, and template file

2016-12-05 11:09 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.less
>      }
Not your changes, but could you please move the `.h4` styles from line 13 inside this `h1`?
```
h1 {
    ...

    &.h4 {
        display: inline-block;
        margin-bottom: 27px;
        padding-bottom: 15px;
        padding-left: 15px;
     }
}

```

2016-12-05 11:09 UTC, santiph commented on assets/app/features/upgrade/i18n/en.json
> +                        "description": "Long description here"
Where does this copy come from?

2016-12-05 11:09 UTC, santiph commented on assets/app/features/upgrade/i18n/en.json
> +                        "description": "Long description here"
Also, where is it being used in the template?

2016-12-05 11:21 UTC, Itxaka commented on assets/app/features/upgrade/i18n/en.json
> +                        "description": "Long description here"
Nowhere. I added it when I believed the scope for the change was bigger. Let me remove it....

2016-12-05 11:22 UTC, Itxaka commented on assets/app/widgets/crowbar-circle/crowbar-circle.directive.js
> +        };
This is all done by css so there is no need for templateurl or template file to make the circles in this directive.

2016-12-05 11:25 UTC, Itxaka commented on assets/app/widgets/crowbar-circle/crowbar-circle.less
> +  background-color: #00b2e2;
done!

2016-12-05 11:25 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.less
>      }
done!

2016-12-05 11:25 UTC, Itxaka commented on assets/app/features/upgrade/i18n/en.json
> +                        "description": "Long description here"
removed!

2016-12-06 15:40 UTC, santiph requested changes
Please, address the requested changes

2016-12-06 15:40 UTC, santiph commented on assets/app/features/upgrade/i18n/en.json
> +                        "description": "In normal mode, each node will be rebooted during the upgrade process, including the workloads running in them.</br></br>In order to proceed in non-disruptive
Please avoid HTML tags in language files

2016-12-06 15:40 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    p(
AFAIK, `nil` is not a valid datatype in javascript. ;)
I'd rather use `ng-if` over `ng-show` (http://stackoverflow.com/questions/19177732/what-is-the-difference-between-ng-if-and-ng-show-ng-hide)
Also, I think you can still use one single line
`p(translate='', ng-show='upgradeLandingVm.mode.type == null') upgrade.steps.landing.mode.description`

2016-12-06 15:40 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    p(
I think more than 1 `p` is required, according to the comps. Please avoid using html tags in the language file

2016-12-06 15:40 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +                            return check == true
`===`

2016-12-06 15:40 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +            .mode.pull-left(ng-class="{'active': upgradeLandingVm.mode.active, 'inactive': !upgradeLandingVm.mode.valid}")
Can't `upgradeLandingVM.prechecks.valid` be used to determine wether the second steps is enabled/active or not?

2016-12-06 15:40 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> -        li(translate='') upgrade.steps.landing.requirements.point3
Please be sure to remove those keys from the language file if not needed

2016-12-06 15:40 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                ng-disabled="upgradeLandingVm.prechecks.running",
indentation

2016-12-06 15:40 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    ) upgrade.steps.landing.mode.nondisruptive.description
Newline at the end of the file

2016-12-06 15:46 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    p(
umm, good point on the ng-if, I did not know there was such a huge difference between both methods.

2016-12-06 15:47 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +            .mode.pull-left(ng-class="{'active': upgradeLandingVm.mode.active, 'inactive': !upgradeLandingVm.mode.valid}")
now I feel dumb...

2016-12-06 16:02 UTC, Itxaka commented on assets/app/features/upgrade/i18n/en.json
> +                        "description": "In normal mode, each node will be rebooted during the upgrade process, including the workloads running in them.</br></br>In order to proceed in non-disruptive
done

2016-12-06 16:02 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> -        li(translate='') upgrade.steps.landing.requirements.point3
done

2016-12-06 16:02 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                ng-disabled="upgradeLandingVm.prechecks.running",
done

2016-12-06 16:02 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +            .mode.pull-left(ng-class="{'active': upgradeLandingVm.mode.active, 'inactive': !upgradeLandingVm.mode.valid}")
done

2016-12-06 16:02 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    p(
done

2016-12-06 16:03 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    ) upgrade.steps.landing.mode.nondisruptive.description
done

2016-12-06 16:08 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    p(
done

2016-12-06 16:18 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                        p(translate='', ng-if='upgradeLandingVm.mode.type == "non-disruptive"') upgrade.steps.landing.mode.nondisruptive.title
`p(ng-if='upgradeLandingVm.mode.type == "non-disruptive"')
    strong(translate='') upgrade.steps.landing.mode.nondisruptive.title`

2016-12-06 16:28 UTC, santiph requested changes

2016-12-06 16:28 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    visible="upgradeLandingVm.prepare.spinnerVisible")
indentation

2016-12-06 16:28 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                        p(translate='', ng-if='upgradeLandingVm.mode.type == "non-disruptive"') upgrade.steps.landing.mode.nondisruptive.title
```
p(ng-if='upgradeLandingVm.mode.type == "non-disruptive"')
    strong(translate='') upgrade.steps.landing.mode.nondisruptive.title
```

2016-12-06 16:28 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                            'spinner-visible': upgradeLandingVm.prechecks.spinnerVisible,\
indentation

2016-12-06 16:28 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +        function continueNormal() {
Docblock

2016-12-06 16:28 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +        function updateMode() {
docblock

2016-12-06 16:28 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +            if (vm.mode.type == 'non-disruptive') {
Should the upgrade type be stored as constants? What do you think?
Use `===`

2016-12-06 16:28 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +            .upgrade.pull-left(ng-class="{'active': upgradeLandingVm.mode.valid, 'inactive': !upgradeLandingVm.mode.valid}")
Also, can't we use just one class here as a toggle for active/inactive and rely on the default color/value for the opposite state?

2016-12-06 16:28 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    p(translate='', ng-if='upgradeLandingVm.mode.type == "disruptive"') upgrade.steps.landing.mode.normal.description1
Please, use a container and only one ng-if to avoid unnecessary watchers. Same on line 55
Also use `===`

2016-12-06 16:28 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    p(translate='', ng-if='upgradeLandingVm.mode.type == false') upgrade.steps.landing.mode.description
please, switch to `===` here and the next occurrences

2016-12-07 10:42 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +        function updateMode() {
done

2016-12-07 10:42 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +            if (vm.mode.type == 'non-disruptive') {
done

2016-12-07 10:42 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +        function continueNormal() {
done

2016-12-07 10:42 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                            'spinner-visible': upgradeLandingVm.prechecks.spinnerVisible,\
done

2016-12-07 10:42 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +            .upgrade.pull-left(ng-class="{'active': upgradeLandingVm.mode.valid, 'inactive': !upgradeLandingVm.mode.valid}")
actually I only needed the active class here it seems. I think is a leftover from before.

2016-12-07 10:42 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    visible="upgradeLandingVm.prepare.spinnerVisible")
done

2016-12-07 10:42 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    p(translate='', ng-if='upgradeLandingVm.mode.type == false') upgrade.steps.landing.mode.description
done

2016-12-07 10:42 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                    p(translate='', ng-if='upgradeLandingVm.mode.type == "disruptive"') upgrade.steps.landing.mode.normal.description1
done

2016-12-07 10:42 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page.jade
> +                        p(translate='', ng-if='upgradeLandingVm.mode.type == "non-disruptive"') upgrade.steps.landing.mode.nondisruptive.title
does not work, already tried.

2016-12-07 16:25 UTC, santiph requested changes

2016-12-07 16:25 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +                            return check === true
missing semicolon

2016-12-07 16:25 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +                            updateMode()
missing semicolon

2016-12-08 13:35 UTC, skazi0 requested changes
minor things to adjust

2016-12-08 13:35 UTC, skazi0 commented on routes/api/upgrade.js
> +    tested_step = 'admin_upgrade',
this should be `upgrade_prechecks` if you want to be on the first step.

2016-12-08 13:35 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
>                      //Success handler. Al precheck passed successfully:
old typo. consider fixing.

2016-12-08 13:35 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +                                if (value.required == true) {
Why not simply `if (value.required) {`?

With the rename mentioned above it would be `if (check.required) {` which is way easier to understand than `if (value.required == true) {`.

2016-12-08 13:35 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
>                          _.forEach(response.data.checks, function(value, key) {
Renaming `value` and `key` to e.g. `check`, `checkKey` would make the code below be more readable.

2016-12-08 13:35 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +                        vm.prechecks.valid = checksValidity.every(function (check) {
The values stored in `checksValidity` are not "checks" but info on the "passed" status so again if you renamed the argument from `check` to e.g. `checkPassed` the test function would not need an explicit comparison to `true`.

2016-12-08 13:35 UTC, skazi0 commented on assets/app/features/upgrade/templates/landing-page_step3.partial.jade
> +        crowbar-circle.pull-left(ng-class="{'active': upgradeLandingVm.mode.valid}") 3
With this approach (i.e. binding css classes to models directly) you don't need a directive at all. To make better use of the possibilities you get with a directive, you should make `active` an attribute of the directive, bind model to this and use link function to attach behavior to changes in `active` model (i.e. update css classes).

2016-12-08 13:35 UTC, skazi0 commented on assets/app/features/upgrade/templates/landing-page_step3.partial.jade
> +    p(translate='') upgrade.steps.landing.upgrade.description
Visually I think there should be some more free space between the steps (i.e. above `(2)`) and less above "Begin Upgrade" button (see: https://raw.githubusercontent.com/crowbar/crowbar-ui/wiki-assets/upgrade67/landing%20page2.png).

2016-12-08 13:44 UTC, skazi0 commented
Note that there is a small rebase needed after my recent changes. "Check" button is now disabled when the prepare step is ongoing to avoid running prechecks in parallel.

2016-12-08 14:08 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +                                if (value.required == true) {
If comparison is still preferred for some reason, use strict equality instead `===`

2016-12-08 14:13 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page_step3.partial.jade
> +        crowbar-circle.pull-left(ng-class="{'active': upgradeLandingVm.mode.valid}") 3
+1 to move such behavior to the direcive

2016-12-08 14:15 UTC, santiph commented on assets/app/features/upgrade/templates/landing-page_step3.partial.jade
> +    p(translate='') upgrade.steps.landing.upgrade.description
Alignment is yet to be implemented.
For further reference, please refer to https://github.com/crowbar/crowbar-ui/blob/wiki-assets/upgrade67/crowbar-wizard-comp-colours-and-spacing.pdf

2016-12-08 15:33 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
>                      //Success handler. Al precheck passed successfully:
fixed

2016-12-08 15:33 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
>                          _.forEach(response.data.checks, function(value, key) {
done

2016-12-08 15:33 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +                                if (value.required == true) {
Done. Forgot to remove it

2016-12-08 15:33 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-landing.controller.js
> +                        vm.prechecks.valid = checksValidity.every(function (check) {
done

2016-12-08 15:33 UTC, Itxaka commented on assets/app/features/upgrade/templates/landing-page_step3.partial.jade
> +        crowbar-circle.pull-left(ng-class="{'active': upgradeLandingVm.mode.valid}") 3
I did understand 1/10th of those words.

I will check this further, I dont know a lot about directives : <

2016-12-09 08:13 UTC, skazi0 commented on assets/app/features/upgrade/templates/landing-page_step3.partial.jade
> +        crowbar-circle.pull-left(ng-class="{'active': upgradeLandingVm.mode.valid}") 3
Directives are hard on the surface but once you get inside they are pretty nice concept to work with.

Take a look around here: https://github.com/crowbar/crowbar-ui/blob/master/assets/app/widgets/suse-lazy-spinner/suse-lazy-spinner.directive.js#L27 for some hints on how to handle custom attributes (by coincidence this one is also called 'active'). You generally need to create 'link' function which is called by angular when the directive is attached to specific DOM element. This is the only place where you get a DOM handle to work with. You can register handlers and watches here to define your directive's behavior.

Another place to look at is just above (https://github.com/crowbar/crowbar-ui/blob/master/assets/app/widgets/suse-lazy-spinner/suse-lazy-spinner.directive.js#L15). This is where you define "isolated scope" for the directive. This means that each instance of this directive will have it's own "interface" and will not rely on the parent scope.

Final piece is something you probably saw already: https://github.com/crowbar/crowbar-ui/blob/master/assets/app/features/upgrade/templates/landing-page.jade#L38 binding 'active' attribute of specific instance of the directive with some external model.

2016-12-09 13:46 UTC, Itxaka commented
rebased and squased. @skazi0 change to the check button maintained at: https://github.com/crowbar/crowbar-ui/pull/96/files#diff-8c2d3eab70c26f7a094729cc6f5382c1R10

2016-12-12 08:43 UTC, skazi0 approved these changes

2016-12-14 11:09 UTC, santiph requested changes
Unit tests for the directive are still missing

2016-12-14 11:09 UTC, santiph commented on assets/app/widgets/crowbar-circle/crowbar-circle.directive.js
> +                scope.$watch('active', function(newVal) {
Is $watch needed here? Isn't it automatically updated?

2016-12-14 11:15 UTC, skazi0 commented on assets/app/widgets/crowbar-circle/crowbar-circle.directive.js
> +                scope.$watch('active', function(newVal) {
This is the main functionality of this directive. Monitor `active` scope attribute and set CSS classes on DOM element appropriately.

2016-12-14 11:25 UTC, santiph commented on assets/app/widgets/crowbar-circle/crowbar-circle.directive.js
> +                scope.$watch('active', function(newVal) {
I know, but I think I remember directives can use two way data binding without explicitly call $watch()

2016-12-14 11:27 UTC, Itxaka commented on assets/app/widgets/crowbar-circle/crowbar-circle.directive.js
> +                scope.$watch('active', function(newVal) {
I actually thougth that indeed it was a 2 way binding but it didnt seem to work unless I set a watcher. Maybe Im doing it wrong?

2016-12-14 11:27 UTC, skazi0 commented on assets/app/widgets/crowbar-circle/crowbar-circle.directive.js
> +                scope.$watch('active', function(newVal) {
This is not data binding. What would you bind the scope attribute to? DOM elements are not models you can bind to.

2016-12-14 16:58 UTC, Itxaka commented
@santiph you force pushed commits that have nothing to do with this commit (suse footer, f.e). I spent quite some time rebasing everything to be clearer the other day :sob:

2016-12-15 09:32 UTC, santiph commented
@Itxaka I didn't use force push. Changes on widgets were required to apply the new look and feel on the landing page

2016-12-15 09:44 UTC, santiph approved these changes

2016-12-15 10:24 UTC, skazi0 commented
@santiph maybe you didn't force-push but you did merge master into feature branch. You should rebase instead of merging like this.
Rebase is not recommended after the branch was made public but I think that we can safely ignore this recommendation in our workflow. The reason is that PR branches during review can be considered semi-public, i.e. rewriting history of those branches should not be a surprise for people watching the PR. It's likely that there will be no people using the PR branch without knowing about the PR.

2016-12-15 11:25 UTC, merged

2016-12-15 11:28 UTC, santiph commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) S51P15 #35 Layout - New Design](https://trello.com/c/e15Q4gsi/188-2-s51p15-35-layout-new-design)

2016-12-20 11:03 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(?) Update UI Steps - move to New Design](https://trello.com/c/ZBzjl4Ay/218-update-ui-steps-move-to-new-design)