upgrade: Database page refresh handling
crowbar/crowbar-ui pull request #99
Opened 2016-12-07 11:37 UTC by skazi0

temp based on #95

2016-12-07 11:37 UTC, skazi0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) S51P13 (S50P16) #27 Restore Last Step](https://trello.com/c/6q4ETmgv/160-2-s51p13-s50p16-27-restore-last-step)

2016-12-07 12:36 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.js
> +                undefined, upgradeStepsFactory.setCurrentStepCompleted);
shouldnt we pass a function here to `onRunning` so if its running we can disable buttons and so on?

2016-12-07 12:36 UTC, Itxaka commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.js
> +                undefined, upgradeStepsFactory.setCurrentStepCompleted);
ah shit, this is done in the syncStatusFlags `flagsObject.running`

I didnt see that, deleting the comments!

2016-12-07 12:38 UTC, Itxaka approved these changes
Really really like it, very elegant!

2016-12-08 11:27 UTC, santiph requested changes

2016-12-08 11:27 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.js
> +        function activate() {
Missing docblock.
Same for the other functions

2016-12-08 11:27 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.spec.js
> +        spyOn(upgradeStepsFactory, 'setCurrentStepCompleted');
What is this spy being used for?

2016-12-08 12:18 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.spec.js
> +        spyOn(upgradeStepsFactory, 'setCurrentStepCompleted');
This is shortcut for quick mocking of individual service functions. It's used later in `toHaveBeenCalledWith()` expectation.

2016-12-08 12:19 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.js
> +        function activate() {
I haven't created any other functions and `activate()` being part of the pattern from JP's guidelines doesn't need documenting imho.

2016-12-08 14:00 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.js
> +        function activate() {
Please, document the functions or create a tech debt to track them later on.

2016-12-08 14:03 UTC, santiph submitted a review, later dismissed

2016-12-08 14:03 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.spec.js
> +        spyOn(upgradeStepsFactory, 'setCurrentStepCompleted');
I see it for `upgradeStatusFactory`, but not for `upgradeStepsFactory`

2016-12-08 14:03 UTC, santiph commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.js
> +        function activate() {
Please, document the functions or create a tech debt to track them later on.

2016-12-08 14:27 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.spec.js
> +        spyOn(upgradeStepsFactory, 'setCurrentStepCompleted');
`upgradeStepsFactory` is referred to in line 75.

PS. this was your idea to mock this function and use it as argument to `toHaveBeenCalledWith()` :)

2016-12-08 14:29 UTC, skazi0 commented on assets/app/features/upgrade/controllers/upgrade-database-configuration.controller.js
> +        function activate() {
I'm not going to document `activate()` function and the rest is out of scope of this PR. If you want to do some general "catching up on the docs" please create a card for that yourself.

2016-12-13 14:17 UTC, merged